// app/layout.tsx
import { AuthProvider } from "@/app/components/Providers";
import { CartProvider } from "@/app/pages/CartContext/page";
import { SelectedCategoryProvider } from "@/app/pages/SelectedCategoryForProductContext/page";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <SelectedCategoryProvider>{children}</SelectedCategoryProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
